#!/bin/bash

. globalVariables

# Specific Experiments

echo -e "\nIER Shortest Path Methods"

# Figure 4a
exp_prefix="ier_versions"
exp_stats_file="${exp_prefix}_varyk.txt"
# bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Gtree;dark-magenta;12,IER-MGt;black;3,IER-PHL;dark-orange;8,IER-TNR;blue;2,IER-CH;green;1" default default "right bottom,horizontal maxcols 2,-2" default $default_density_string
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Dijk;navy;1,MGtree;black;12,PHL;dark-magenta;2,TNR;dark-orange;6,CH;dark-green;3" default default "right bottom,vertical maxrows 2,-3.5" default $default_density_string

# Figure 4b
exp_prefix="ier_versions"
exp_stats_file="${exp_prefix}_varyd.txt"
# bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Gtree;dark-magenta;12,IER-MGt;black;3,IER-PHL;dark-orange;8,IER-TNR;blue;2,IER-CH;green;1" default default "right top,vertical maxrows 2,-2" $default_k default
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Dijk;navy;1,MGtree;black;12,PHL;dark-magenta;2,TNR;dark-orange;6,CH;dark-green;3" default default "right top,horizontal maxcols 2,-3" $default_k default

# Figure 
exp_prefix="ier_versions"
exp_stats_file="${exp_prefix}_varyn.txt"
# bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Gtree;dark-magenta;12,IER-MGt;black;3,IER-PHL;dark-orange;8,IER-TNR;blue;2,IER-CH;green;1" all default "right top,vertical maxrows 2,-2" $default_k $default_density_string
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Dijk;navy;1,MGtree;black;12,PHL;dark-magenta;2,TNR;dark-orange;6,CH;dark-green;3" all default "right bottom,horizontal maxcols 2,-3" $default_k $default_density_string
# bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "MGtree;black;3,PHL;dark-magenta;8,TNR;dark-orange;2,CH;dark-green;1" all default "right top,horizontal maxcols 2,-2" $default_k $default_density_string


echo -e "\nDisBrw Improvements"

# DB-ENN Optimisation

# Figure
exp_prefix="silc_dbenn"
exp_stats_file="${exp_prefix}_varyk.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "DisBrw;dark-red;4,DB-ENN;black;12" default default "left top,vertical,-1" default $default_density_string

# Figure 
exp_prefix="silc_dbenn"
exp_stats_file="${exp_prefix}_varyd.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "DisBrw;dark-red;4,DB-ENN;black;12" default default "left bottom,vertical,-1" $default_k default


# Optimisation on Non-Highway Dataset

# Figure 6a (uses linear scale for y - query time)
exp_prefix="silc_opt"
exp_stats_file="${exp_prefix}_varyk.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "DisBrw;dark-red;4,OptDisBrw;dark-magenta:3" default "7,Query Time ({/Symbol m}s),'',''" "left top,vertical,-3" default $default_density_string

# Figure 6b (uses linear scale for y - query time)
exp_prefix="silc_opt"
exp_stats_file="${exp_prefix}_varyd.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "DisBrw;dark-red;4,OptDisBrw;dark-magenta:3" default "7,Query Time ({/Symbol m}s),'',''" "right top,vertical,-3" $default_k default

# Optimisation on Highway Datasets

# Figure 5a (on highway dataset NA)
exp_prefix="silc_opt_hwy_na"
exp_stats_file="${exp_prefix}_varyk.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "DisBrw;dark-red;4,OptDisBrw;dark-magenta:3" NA default "right bottom,vertical,-3" default $default_density_string

# Figure 5b (on highway dataset NA)
exp_stats_file="${exp_prefix}_varyd.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "DisBrw;dark-red;4,OptDisBrw;dark-magenta:3" NA default "right top,vertical,-3" $default_k default



echo -e "\nG-tree Leaf Search Improvement"

# Figure 7a
exp_prefix="gtree_leaf_search_opt_multik"
exp_stats_file="${exp_prefix}_varyd.txt"
output_file="${exp_prefix}_${default_network}_varying_density_${default_type}.txt"
figure_file="${exp_prefix}_${default_network}_varying_density_${default_type}"
cat $stats_dir/$exp_stats_file | bash splitStatsRows $1 > $fig_data_dir/$output_file # Insert two newlines between methods
bash generateFigure $fig_dir/$figure_file $fig_data_dir/$output_file "9,Density,$x_tics,'',logscale,''" \
"7,Query Time ({/Symbol m}s),logscale,'10^%T'" "k=1 (Bef);blue;2,k=1 (Aft);red;12,k=10 (Bef);black;10,k=10 (Aft);dark-orange;4" "right top,horizontal,-3"

# Figure 7b
exp_prefix="gtree_leaf_search_opt_usa_multik"
exp_stats_file="${exp_prefix}_varyd.txt"
output_file="${exp_prefix}_USA_varying_density_${default_type}.txt"
figure_file="${exp_prefix}_USA_varying_density_${default_type}"
cat $stats_dir/$exp_stats_file | bash splitStatsRows $1 > $fig_data_dir/$output_file # Insert two newlines between methods
bash generateFigure $fig_dir/$figure_file $fig_data_dir/$output_file "9,Density,$x_tics,'',logscale,''" \
"7,Query Time ({/Symbol m}s),logscale,'10^%T'" "k=1 (Bef);blue;2,k=1 (Aft);red;12,k=10 (Bef);black;10,k=10 (Aft);dark-orange;4" "right top,horizontal,-3"


echo -e "\nG-tree Distance Matrix Implementations"

# Figure 8a
exp_prefix="gtree_dist_matrix_versions"
exp_stats_file="${exp_prefix}_varyk.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Chained Hashing;navy;1,Quad. Probing;dark-green;10,Array;red;8" default default "right bottom,vertical,-3" default $default_density_string

# Figure 8b
exp_prefix="gtree_dist_matrix_versions"
exp_stats_file="${exp_prefix}_varyd.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "Chained Hashing;navy;1,Quad. Probing;dark-green;10,Array;red;8" default default "right top,vertical,-3" $default_k default


echo -e "\nG-tree Path Cost vs Road Nodes Bypassed"

# Figure 13b
exp_prefix="road_stats"
exp_stats_file="$exp_prefix.txt"
temp_exp_stats_file="temp_$exp_prefix.txt"
cat $stats_dir/$exp_stats_file | bash extractColumnAndAppend 4 "nodes_bypassed=([[:digit:]]+)" > $stats_dir/$temp_exp_stats_file # Column 13 - Nodes Bypassed
# cat $stats_dir/$temp_exp_stats_file | bash extractColumnAndAppend 4 "rnets_bypassed=([[:digit:]]+)" > $stats_dir/$exp_stats_file # Column 14 - Rnets Bypassed
# cat $stats_dir/$exp_stats_file | bash extractColumnAndAppend 4 "rnets_evaluated=([[:digit:]]+)" > $stats_dir/$temp_exp_stats_file # Column 15 - Rnets Evaluated
cat $stats_dir/$temp_exp_stats_file > $stats_dir/$exp_stats_file
rm $stats_dir/$temp_exp_stats_file

exp_prefix2="gtree_stats"
exp_stats_file2="$exp_prefix2.txt"
temp_exp_stats_file="temp_$exp_prefix2.txt"
cat $stats_dir/$exp_stats_file2 | bash extractColumnAndAppend 4 "computations_executed=([[:digit:]]+)" > $stats_dir/$temp_exp_stats_file # Column 13 - Computation Executed
cat $stats_dir/$temp_exp_stats_file > $stats_dir/$exp_stats_file2
rm $stats_dir/$temp_exp_stats_file

exp_prefix3="ier_gtree_stats"
exp_stats_file3="$exp_prefix3.txt"
temp_exp_stats_file="temp_$exp_prefix3.txt"
cat $stats_dir/$exp_stats_file3 | bash extractColumnAndAppend 4 "computations_executed=([[:digit:]]+)" > $stats_dir/$temp_exp_stats_file # Column 13 - Computation Executed
cat $stats_dir/$temp_exp_stats_file > $stats_dir/$exp_stats_file3
rm $stats_dir/$temp_exp_stats_file

figure_file="gtree_path_cost_vs_road_nodes_bypassed_varying_total_nodes"
bash generateSpecialFigureGtreeVsRoadStats $stats_dir/$exp_stats_file2 $stats_dir/$exp_stats_file $stats_dir/$exp_stats_file3 $fig_dir/$figure_file


echo -e "\nProgressive INE Improvement"

# Figure 
exp_prefix="ine_improvements"
exp_stats_file="${exp_prefix}_varyk.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "1st Cut;dark-magenta;1,PQueue;dark-green;10,Settled;red:3,Graph;blue;6" default default "right bottom,horizontal maxcols 2,-2" default $default_density_string

# Figure 
exp_prefix="ine_improvements"
exp_stats_file="${exp_prefix}_varyd.txt"
bash createSingleKnnExperimentFigures 13 $exp_stats_file $exp_prefix "1st Cut;dark-magenta;1,PQueue;dark-green;10,Settled;red:3,Graph;blue;6" default default "right top,vertical maxrows 2,-2" $default_k default


# Default Experiments

# Figure 10, 16
bash createIndexExperimentsFigures

# Figure 11a, 12a, 13a
bash createDefaultKnnExperimentFigures 10 0.00100 NW

# Figure 9
bash createDefaultKnnExperimentFigures 10 0.01000 COL density

# Figure 11b, 12b
bash createDefaultKnnExperimentFigures 10 0.00100 USA network # Don't run network (run in previous command)


# Minimum Object Distance Object Sets

# Figure 
echo -e "\nRange Distance Experiments: NW, k=10, d=0.001, m=6"
bash createMinMaxDistObjectsExperimentsFigures min_nd 0.001 "1,2,3,4,5,6" 3 NW;

# Figure 
echo -e "\nRange Distance Experiments: USA, k=10, d=0.001, m=8"
bash createMinMaxDistObjectsExperimentsFigures min_nd 0.001 "1,2,3,4,5,6,7,8" 4 USA;


# Clustered Object Sets

# Figure 
echo -e "\nClustered Experiments: NW, k=10, d=0.001, |C|=5,"
bash createClusteredObjectsExperimentsFigures 0.001 "0.1,0.01,0.001,0.0001" 5 "5,10,25,50,100" NW;


# Real-World Object Sets

bash createRealWorldPOIExperimentsFigures default NW;
bash createRealWorldPOIExperimentsFigures default USA;
