#!/bin/bash

# $1 is column number (starting from 1)
# $2 is matching column value (these rows will be removed)

IFS=$'\t'

while read line; do
    array=(${line})
    column=${array[$(($1-1))]}
    [[ $column != $2 || $line == "" ]] && echo "$line"
done