#!/bin/bash

# $1 is column number (starting from 1)
# $2 3 is pattern to match

IFS=$'\t'

while read line; do
    array=(${line})
    column=${array[$(($1-1))]}
    if [[ $column =~ $2 ]]; then
        value=${BASH_REMATCH[1]}
        echo -e "$line\t$value"
    fi    
done

