#!/bin/bash

. globalVariables

mkdir -p "$idx_dir"
mkdir -p "$stats_dir"
mkdir -p "$obj_idx_dir"
mkdir -p "$sets_dir"
mkdir -p "$data_dir"
mkdir -p "$data_dir/dimacs"
mkdir -p "$data_dir/tpq"
mkdir -p "$fig_dir"
mkdir -p "$fig_data_dir"

# Delete Object Sets/Indexes and Query Point Sets
if [ -z "$obj_idx_dir" ]; then
    echo '$obj_idx_dir is not set'
else
    rm -rf "$obj_idx_dir"/*
fi
if [ -z "$sets_dir" ]; then
    echo '$sets_dir is not set'
else
    rm -rf "$sets_dir"/*
fi

# Optionally Delete Figures and Figure Data
if [[ $1 == "fig+data" ]]; then
    if [ -z "$fig_dir" ]; then
        echo '$fig_dir is not set'
    else
        rm -rf "$fig_dir"/*
        mkdir -p "$fig_dir"
    fi
    if [ -z "$fig_data_dir" ]; then
        echo '$fig_data_dir is not set'
    else
        rm -rf "$fig_data_dir"/*
        mkdir -p "$fig_data_dir"
    fi
fi
